name: Dependabot auto merge

concurrency:
  group: dependabot
  cancel-in-progress: false

permissions:
  id-token: write
  pull-requests: write
  contents: write
  issues: read
  checks: write

on: pull_request_target

jobs:
  fetch-metadata:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    outputs:
      update-type: ${{ steps.metadata.outputs.update-type }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.5.0

  run-tests:
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: ./.github/workflows/run-tests.yml
    with:
      COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
    secrets: inherit

  publish-test-results:
    if: ${{ success() || failure() }}
    needs: [ run-tests ]
    uses: ./.github/workflows/publish-test-results.yml

  process-pull-request:
    runs-on: ubuntu-latest
    needs: [ fetch-metadata, run-tests ]
    steps:
      - name: Enable auto merge for Dependabot PRs
        if: ${{ needs.fetch-metadata.outputs.update-type != 'version-update:semver-major' }}
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --squash "$PR_URL"

      - name: Mark major update
        if: ${{ needs.fetch-metadata.outputs.update-type == 'version-update:semver-major' }}
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh label create major --description "Major version update" --color "b60205"
          gh pr edit "$PR_URL" --add-label "major"
