name: Publish test results

on:
  workflow_call:

permissions:
  id-token: write
  pull-requests: write
  contents: write
  issues: read
  checks: write

jobs:
  publish-test-results:
    runs-on: ubuntu-latest
    steps:
      - name: Download test report
        uses: actions/download-artifact@v8
        with:
          name: Test Report
          path: target/surefire-reports/

      - name: Debugging
        run: |
          ls -la .
          ls -la target
          ls -la target/surefire-reports

      - name: Generate test report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Test Results
          files: ./**/target/**/TEST-*.xml